# Define the one-hot encoded features for categorical variables based on your training data
all_features = [
    "Distance (km)",
    "Duration (hours)",
    "Cruising Altitude (ft)",
    "Wind Speed (km/h)",
    "Temperature (°C)",
    "SAF Percentage",
    "Jet A-1 Percentage",
    "Fuel Consumption (liters)",
    "Passenger Load",
    "Cargo Load (kg)",
    "Aircraft Type_Airbus A320",
    "Aircraft Type_Airbus A350",
    "Aircraft Type_Boeing 737",
    "Aircraft Type_Boeing 777",
    "Aircraft Type_Boeing 787",
    "Departure Airport_AGP",
    "Departure Airport_AMS",
    "Departure Airport_ANR",
    "Departure Airport_ARN",
    "Departure Airport_BCN",
    "Departure Airport_BER",
    "Departure Airport_BLQ",
    "Departure Airport_BRU",
    "Departure Airport_BSL",
    "Departure Airport_CDG",
    "Departure Airport_CPH",
    "Departure Airport_DUS",
    "Departure Airport_EDI",
    "Departure Airport_EIN",
    "Departure Airport_FAO",
    "Departure Airport_FCO",
    "Departure Airport_FRA",
    "Departure Airport_GVA",
    "Departure Airport_HAM",
    "Departure Airport_HEL",
    "Departure Airport_INN",
    "Departure Airport_LGW",
    "Departure Airport_LHR",
    "Departure Airport_LIS",
    "Departure Airport_LYS",
    "Departure Airport_MAD",
    "Departure Airport_MAN",
    "Departure Airport_MUC",
    "Departure Airport_MXP",
    "Departure Airport_NAP",
    "Departure Airport_NCE",
    "Departure Airport_OPO",
    "Departure Airport_ORY",
    "Departure Airport_OSL",
    "Departure Airport_PMI",
    "Departure Airport_RTM",
    "Departure Airport_STN",
    "Departure Airport_SZG",
    "Departure Airport_TLS",
    "Departure Airport_VCE",
    "Departure Airport_VIE",
    "Departure Airport_VLC",
    "Departure Airport_ZRH",
    "Arrival Airport_AGP",
    "Arrival Airport_AMS",
    "Arrival Airport_ANR",
    "Arrival Airport_ARN",
    "Arrival Airport_BCN",
    "Arrival Airport_BER",
    "Arrival Airport_BLQ",
    "Arrival Airport_BRU",
    "Arrival Airport_BSL",
    "Arrival Airport_CDG",
    "Arrival Airport_CPH",
    "Arrival Airport_DUS",
    "Arrival Airport_EDI",
    "Arrival Airport_EIN",
    "Arrival Airport_FAO",
    "Arrival Airport_FCO",
    "Arrival Airport_FRA",
    "Arrival Airport_GVA",
    "Arrival Airport_HAM",
    "Arrival Airport_HEL",
    "Arrival Airport_INN",
    "Arrival Airport_LGW",
    "Arrival Airport_LHR",
    "Arrival Airport_LIS",
    "Arrival Airport_LYS",
    "Arrival Airport_MAD",
    "Arrival Airport_MAN",
    "Arrival Airport_MUC",
    "Arrival Airport_MXP",
    "Arrival Airport_NAP",
    "Arrival Airport_NCE",
    "Arrival Airport_OPO",
    "Arrival Airport_ORY",
    "Arrival Airport_OSL",
    "Arrival Airport_PMI",
    "Arrival Airport_RTM",
    "Arrival Airport_STN",
    "Arrival Airport_SZG",
    "Arrival Airport_TLS",
    "Arrival Airport_VCE",
    "Arrival Airport_VIE",
    "Arrival Airport_VLC",
    "Arrival Airport_ZRH",
]

aircraft_types = [
    "Airbus A320",
    "Airbus A350",
    "Boeing 737",
    "Boeing 777",
    "Boeing 787",
]

departure_airports = [
    "AGP",
    "AMS",
    "ANR",
    "ARN",
    "BCN",
    "BER",
    "BLQ",
    "BRU",
    "BSL",
    "CDG",
    "CPH",
    "DUS",
    "EDI",
    "EIN",
    "FAO",
    "FCO",
    "FRA",
    "GVA",
    "HAM",
    "HEL",
    "INN",
    "LGW",
    "LHR",
    "LIS",
    "LYS",
    "MAD",
    "MAN",
    "MUC",
    "MXP",
    "NAP",
    "NCE",
    "OPO",
    "ORY",
    "OSL",
    "PMI",
    "RTM",
    "STN",
    "SZG",
    "TLS",
    "VCE",
    "VIE",
    "VLC",
    "ZRH",
]

arrival_airports = [
    "AGP",
    "AMS",
    "ANR",
    "ARN",
    "BCN",
    "BER",
    "BLQ",
    "BRU",
    "BSL",
    "CDG",
    "CPH",
    "DUS",
    "EDI",
    "EIN",
    "FAO",
    "FCO",
    "FRA",
    "GVA",
    "HAM",
    "HEL",
    "INN",
    "LGW",
    "LHR",
    "LIS",
    "LYS",
    "MAD",
    "MAN",
    "MUC",
    "MXP",
    "NAP",
    "NCE",
    "OPO",
    "ORY",
    "OSL",
    "PMI",
    "RTM",
    "STN",
    "SZG",
    "TLS",
    "VCE",
    "VIE",
    "VLC",
    "ZRH",
]
